* File: base_inverter.pex.netlist.BASE_INVERTER.pxi
* Created: Mon Oct 17 19:33:48 2022
* 
x_PM_BASE_INVERTER%VDD N_VDD_M1_b VDD N_VDD_M1_d PM_BASE_INVERTER%VDD
x_PM_BASE_INVERTER%IN N_IN_M1_g N_IN_M0_g IN PM_BASE_INVERTER%IN
x_PM_BASE_INVERTER%OUT OUT N_OUT_M1_s N_OUT_M0_s PM_BASE_INVERTER%OUT
x_PM_BASE_INVERTER%GND N_GND_M0_b GND N_GND_M0_d PM_BASE_INVERTER%GND
